services:
    compras:
        container_name: compras
        image: compras:latest
        build:
            context: ../
            dockerfile: ./deploy/Dockerfile
        env_file:
            - .env
        ports:
            - "${APP_PORT:-9002}:80"
        # Correção para funcionar com banco do host
        network_mode: bridge
        extra_hosts:
            - "database:host-gateway"
        depends_on:
          - scrapper
        links:
          - scrapper

    scrapper:
        container_name: scrapper
        build: ../scrapper
        network_mode: bridge